[tool.poetry]
name = "agrifood-api"
version = "0.1.0"
description = "World Bank Agrifood project's API"
authors = ["Development Seed <info@ds.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.109.0"
uvicorn = {extras = ["standard"], version = "^0.27.0.post1"}
openai = "^1.10.0"
load-dotenv = "^0.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
